services:
  postgres:
    image: postgres:17-alpine
    container_name: brazil-energy-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  airflow:
    build:
      context: .
      dockerfile: Dockerfile

    image: brazil-energy-airflow:local

    container_name: brazil-energy-airflow

    depends_on:
      postgres:
        condition: service_healthy
    
    env_file:
      - .env

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      POSTGRES_HOST: postgres

    ports:
      - "8080:8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data

    command: standalone

volumes:
  postgres_data:

